/**
 * Test Scenarios Definition
 * Defines all test scenarios from the presentation document
 */

import type { TestScenario } from "./types";

export const TEST_SCENARIOS: TestScenario[] = [
  {
    id: "happy-path",
    name: "Complete Happy Path Flow",
    description:
      "Full lifecycle: Customer request → Admin assigns → Partner confirms → Completion → Closure",
    category: "flow",
    steps: [
      {
        id: "create-request",
        title: "Customer Submits Request",
        description: "Simulate customer creating a service request from mobile app",
        status: "pending",
      },
      {
        id: "admin-review",
        title: "Admin Reviews Request",
        description: "Portal admin views new unassigned request",
        status: "pending",
      },
      {
        id: "suggest-branch",
        title: "System Suggests Branch",
        description: "System calculates and suggests nearest partner branch",
        status: "pending",
      },
      {
        id: "assign-request",
        title: "Admin Assigns to Partner",
        description: "Request assigned to partner branch with 15-min timer",
        status: "pending",
      },
      {
        id: "partner-confirm",
        title: "Partner Confirms Request",
        description: "Partner accepts the request within time limit",
        status: "pending",
      },
      {
        id: "update-progress",
        title: "Partner Updates Progress",
        description: 'Status updated to "In Progress"',
        status: "pending",
      },
      {
        id: "complete-work",
        title: "Partner Completes Work",
        description: "Partner marks request as completed",
        status: "pending",
      },
      {
        id: "admin-verify",
        title: "Admin Verifies Completion",
        description: "Admin contacts customer and verifies satisfaction",
        status: "pending",
      },
      {
        id: "close-request",
        title: "Admin Closes Request",
        description: "Request marked as closed, metrics updated",
        status: "pending",
      },
    ],
  },
  {
    id: "rejection-flow",
    name: "Partner Rejection & Reassignment",
    description: "Test flow when partner rejects request and admin reassigns",
    category: "flow",
    steps: [
      {
        id: "create-request",
        title: "Customer Submits Request",
        description: "Create new service request",
        status: "pending",
      },
      {
        id: "assign-partner-a",
        title: "Admin Assigns to Partner A",
        description: "Initial assignment to first partner",
        status: "pending",
      },
      {
        id: "partner-reject",
        title: "Partner A Rejects",
        description: 'Partner rejects with reason "Fully booked"',
        status: "pending",
      },
      {
        id: "admin-notified",
        title: "Admin Receives Notification",
        description: "Verify admin gets immediate rejection notification",
        status: "pending",
      },
      {
        id: "request-unassigned",
        title: "Request Back to Queue",
        description: "Request returns to unassigned status",
        status: "pending",
      },
      {
        id: "reassign-partner-b",
        title: "Admin Reassigns to Partner B",
        description: "Assign to alternative partner",
        status: "pending",
      },
      {
        id: "partner-b-confirm",
        title: "Partner B Confirms",
        description: "Second partner accepts the request",
        status: "pending",
      },
      {
        id: "verify-timeline",
        title: "Verify Complete Timeline",
        description: "Check rejection and reassignment logged correctly",
        status: "pending",
      },
    ],
  },
  {
    id: "sla-timeout",
    name: "SLA Timeout (15-Minute Breach)",
    description: "Test automatic handling when partner doesn't respond in time",
    category: "edge-case",
    steps: [
      {
        id: "create-assign",
        title: "Create and Assign Request",
        description: "Setup: Customer request assigned to partner",
        status: "pending",
      },
      {
        id: "wait-10-min",
        title: "Wait 10 Minutes",
        description: "Simulate 10 minutes passing (reminder should trigger)",
        status: "pending",
      },
      {
        id: "verify-reminder",
        title: "Verify Reminder Sent",
        description: "Check that partner received reminder notification",
        status: "pending",
      },
      {
        id: "wait-15-min",
        title: "Wait Full 15 Minutes",
        description: "Simulate SLA timeout",
        status: "pending",
      },
      {
        id: "auto-unassign",
        title: "Verify Auto-Unassignment",
        description: "Request should be automatically unassigned",
        status: "pending",
      },
      {
        id: "admin-sla-alert",
        title: "Admin SLA Breach Alert",
        description: "Verify admin receives SLA breach notification",
        status: "pending",
      },
      {
        id: "log-timeout",
        title: "Verify Timeout Logged",
        description: "Check timeout recorded in system logs",
        status: "pending",
      },
    ],
  },
  {
    id: "multi-requests",
    name: "Multiple Concurrent Requests",
    description: "Test system handling 10 simultaneous requests",
    category: "performance",
    steps: [
      {
        id: "create-10-requests",
        title: "Create 10 Requests",
        description: "Different categories, locations, and customers",
        status: "pending",
      },
      {
        id: "admin-view-all",
        title: "Admin Views All Requests",
        description: "Verify all requests visible in dashboard",
        status: "pending",
      },
      {
        id: "filter-by-category",
        title: "Filter and Sort",
        description: "Test filtering by category and sorting by date",
        status: "pending",
      },
      {
        id: "assign-all",
        title: "Assign to Multiple Partners",
        description: "Distribute requests across 3 partners",
        status: "pending",
      },
      {
        id: "partners-respond",
        title: "Partners Respond",
        description: "Multiple partners confirm requests",
        status: "pending",
      },
      {
        id: "concurrent-updates",
        title: "Concurrent Status Updates",
        description: "Partners update status simultaneously",
        status: "pending",
      },
      {
        id: "verify-no-conflicts",
        title: "Verify Data Integrity",
        description: "Check no data mixing or conflicts",
        status: "pending",
      },
      {
        id: "verify-timelines",
        title: "Verify All Timelines",
        description: "Each request has accurate timeline",
        status: "pending",
      },
    ],
  },
  {
    id: "branch-selection",
    name: "Branch Selection by Location",
    description: "Test automatic branch suggestion based on GPS proximity",
    category: "flow",
    steps: [
      {
        id: "setup-branches",
        title: "Setup Partner Branches",
        description: "Partner has 3 branches at different locations",
        status: "pending",
      },
      {
        id: "request-near-main",
        title: "Request Near Main Branch",
        description: "Customer location closest to main branch",
        status: "pending",
      },
      {
        id: "verify-suggestion-main",
        title: "Verify Main Branch Suggested",
        description: "System should suggest main branch",
        status: "pending",
      },
      {
        id: "request-near-north",
        title: "Request Near North Branch",
        description: "Customer location closest to north branch",
        status: "pending",
      },
      {
        id: "verify-suggestion-north",
        title: "Verify North Branch Suggested",
        description: "System should suggest north branch",
        status: "pending",
      },
      {
        id: "equidistant-location",
        title: "Equidistant Customer",
        description: "Customer equally distant from 2 branches",
        status: "pending",
      },
      {
        id: "verify-all-shown",
        title: "Verify All Options Shown",
        description: "All branches shown with distances",
        status: "pending",
      },
    ],
  },
  {
    id: "pickup-options",
    name: "Different Pickup Options",
    description: 'Test "Service at Location" vs "Drop-off at Center"',
    category: "flow",
    steps: [
      {
        id: "service-at-location",
        title: 'Create "Service at Location"',
        description: "Customer selects on-site service",
        status: "pending",
      },
      {
        id: "select-specific-service",
        title: "Select Specific Service",
        description: "Customer must choose specific service type",
        status: "pending",
      },
      {
        id: "partner-sees-location",
        title: "Partner Sees Customer Location",
        description: "Partner can view exact service location",
        status: "pending",
      },
      {
        id: "dropoff-request",
        title: 'Create "Drop-off" Request',
        description: "Customer will bring vehicle to center",
        status: "pending",
      },
      {
        id: "category-only",
        title: "Category Selection Only",
        description: "Only category required for drop-off",
        status: "pending",
      },
      {
        id: "partner-sees-center",
        title: "Partner Sees Center Location",
        description: "Service will be at partner center",
        status: "pending",
      },
      {
        id: "verify-workflows",
        title: "Verify Different Workflows",
        description: "Each pickup option has appropriate workflow",
        status: "pending",
      },
    ],
  },
  {
    id: "multilang",
    name: "Multi-language (EN/AR)",
    description: "Test English and Arabic with RTL support",
    category: "flow",
    steps: [
      {
        id: "admin-switch-arabic",
        title: "Admin Switches to Arabic",
        description: "Change portal language to Arabic",
        status: "pending",
      },
      {
        id: "verify-rtl",
        title: "Verify RTL Layout",
        description: "Check right-to-left layout applied",
        status: "pending",
      },
      {
        id: "assign-request-ar",
        title: "Assign Request in Arabic",
        description: "Complete assignment in Arabic interface",
        status: "pending",
      },
      {
        id: "partner-english",
        title: "Partner Uses English",
        description: "Partner portal in English (LTR)",
        status: "pending",
      },
      {
        id: "confirm-request-en",
        title: "Confirm Request in English",
        description: "Partner confirms using English interface",
        status: "pending",
      },
      {
        id: "verify-data-consistency",
        title: "Verify Data Consistency",
        description: "Actual data not translated, only UI",
        status: "pending",
      },
      {
        id: "verify-notifications",
        title: "Verify Localized Notifications",
        description: "Notifications in user's preferred language",
        status: "pending",
      },
    ],
  },
  {
    id: "reports",
    name: "Reports & Analytics",
    description: "Test all report generation and export functionality",
    category: "flow",
    steps: [
      {
        id: "requests-report",
        title: "Generate Requests Report",
        description: "Last 30 days, all categories",
        status: "pending",
      },
      {
        id: "verify-requests-data",
        title: "Verify Requests Data",
        description: "Check totals, statuses, and metrics",
        status: "pending",
      },
      {
        id: "partner-performance",
        title: "Generate Partner Performance",
        description: "Performance metrics for specific partner",
        status: "pending",
      },
      {
        id: "verify-partner-metrics",
        title: "Verify Partner Metrics",
        description: "Confirmation time, completion time, rejection rate",
        status: "pending",
      },
      {
        id: "branch-efficiency",
        title: "Generate Branch Efficiency",
        description: "Efficiency report per branch",
        status: "pending",
      },
      {
        id: "verify-branch-data",
        title: "Verify Branch Data",
        description: "Requests per branch, avg distance, completion rate",
        status: "pending",
      },
      {
        id: "export-excel",
        title: "Export to Excel",
        description: "Export all reports to Excel format",
        status: "pending",
      },
      {
        id: "verify-export-data",
        title: "Verify Exported Data",
        description: "Check data accuracy and formatting",
        status: "pending",
      },
    ],
  },
  {
    id: "permissions",
    name: "Role-Based Access Control",
    description: "Test permissions for different user roles",
    category: "security",
    steps: [
      {
        id: "admin-full-access",
        title: "Admin Full Access",
        description: "Verify admin can access all features",
        status: "pending",
      },
      {
        id: "partner-limited-access",
        title: "Partner Limited Access",
        description: "Partner can only see assigned requests",
        status: "pending",
      },
      {
        id: "partner-no-admin",
        title: "Partner Cannot Access Admin",
        description: "Partner blocked from admin features",
        status: "pending",
      },
      {
        id: "partner-no-other-requests",
        title: "Partner Cannot See Other Requests",
        description: "Partners can't view other partners' requests",
        status: "pending",
      },
      {
        id: "unauthorized-api",
        title: "Unauthorized API Access",
        description: "API calls without token are rejected",
        status: "pending",
      },
      {
        id: "wrong-role-api",
        title: "Wrong Role API Access",
        description: "Partner can't call admin-only endpoints",
        status: "pending",
      },
      {
        id: "verify-error-messages",
        title: "Verify Error Messages",
        description: "Proper error messages for unauthorized access",
        status: "pending",
      },
    ],
  },
  {
    id: "edge-cases",
    name: "Edge Cases & Error Handling",
    description: "Test error handling and unusual scenarios",
    category: "edge-case",
    steps: [
      {
        id: "invalid-request-data",
        title: "Invalid Request Data",
        description: "Submit request with missing fields",
        status: "pending",
      },
      {
        id: "verify-validation",
        title: "Verify Validation Errors",
        description: "Proper validation messages shown",
        status: "pending",
      },
      {
        id: "concurrent-edits",
        title: "Concurrent Edits",
        description: "Admin and partner edit same request",
        status: "pending",
      },
      {
        id: "verify-conflict-resolution",
        title: "Verify Conflict Resolution",
        description: "System handles concurrent edits correctly",
        status: "pending",
      },
      {
        id: "network-interruption",
        title: "Simulate Network Loss",
        description: "Start operation, interrupt network",
        status: "pending",
      },
      {
        id: "verify-recovery",
        title: "Verify State Recovery",
        description: "System recovers to consistent state",
        status: "pending",
      },
      {
        id: "large-volume",
        title: "Create 100+ Requests",
        description: "Test with large data volume",
        status: "pending",
      },
      {
        id: "verify-performance",
        title: "Verify Performance",
        description: "Pagination works, load times acceptable",
        status: "pending",
      },
    ],
  },
  {
    id: "admin-assignment",
    name: "Admin Assignment Flow",
    description:
      "Complete admin workflow: View queue → Select request → Assign to partner → Partner confirms",
    category: "flow",
    steps: [
      {
        id: "create-unassigned-request",
        title: "Create Unassigned Request",
        description: "Simulate customer creating a service request",
        status: "pending",
      },
      {
        id: "admin-view-queue",
        title: "Admin Views Assignment Queue",
        description: "Admin accesses the assignment queue page",
        status: "pending",
      },
      {
        id: "fetch-partners",
        title: "Fetch Active Partners",
        description: "Retrieve existing active partners from database",
        status: "pending",
      },
      {
        id: "suggest-branches",
        title: "Suggest Nearest Branches",
        description: "Calculate and suggest nearest branches based on GPS",
        status: "pending",
      },
      {
        id: "assign-to-partner",
        title: "Admin Assigns to Partner",
        description: "Assign request to selected partner branch",
        status: "pending",
      },
      {
        id: "verify-assignment",
        title: "Verify Assignment Created",
        description: "Check request status changed to assigned",
        status: "pending",
      },
      {
        id: "verify-sla",
        title: "Verify SLA Deadline Set",
        description: "Confirm 15-minute SLA deadline is set",
        status: "pending",
      },
      {
        id: "partner-receives-notification",
        title: "Partner Receives Notification",
        description: "Verify partner notification was created",
        status: "pending",
      },
      {
        id: "partner-confirms",
        title: "Partner Confirms Request",
        description: "Partner accepts the assigned request",
        status: "pending",
      },
      {
        id: "verify-timeline",
        title: "Verify Complete Timeline",
        description: "Check all status changes logged correctly",
        status: "pending",
      },
    ],
  },
];

